### PR TITLE
Many fixes related to everything

### PR DESCRIPTION
**Pull request by ghost**
These fixes mostly related to translation and to improve translation process.

Please review individually.

### CODE REVIEW

**Comment by ghost** [comment]
@SalaniLeo Could you check when you have time.

**Comment by SalaniLeo** [comment]
yeah, thanks for the many fixes. I'm still waiting for that gtk bug before fixing things myself, but thanks again. Do you have an idea for when the bug will be fixed? Also another thing, before doing more translations I suggest waiting until the bug is fixed, because I will almost surely add/modify things before then so you'll need to update the translations again before a new release.

**Comment by ghost** [comment]
Translation is a simple thing for me. I can translate them again. Fixing other things are important :)

**Comment by ghost** [comment]
About the GTK bug, is there any alternative in libadwaita that can be used?

**Pull request merged**
